name = "miccort-signaling"
main = "src/index.ts"
compatibility_date = "2026-05-12"

[[durable_objects.bindings]]
name = "SIGNALING_HUB"
class_name = "SignalingHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingHub"]
